services:
  db:
    image: mysql:5.7
    container_name: dets_db
    restart: always
    environment:
      MYSQL_DATABASE: detsdb
      MYSQL_USER: detsuser
      MYSQL_PASSWORD: detspassword
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - "./SQL File/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

  phpapp:
    build: .
    container_name: dets_phpapp
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: detsuser
      MYSQL_PASSWORD: detspassword
      MYSQL_DB: detsdb
    volumes:
      - ./dets:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dets_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  db_data:
