version: "3.8"

services:
  web:
    build: .
    container_name: expense_app
    ports:
      - "8081:80"
    volumes:
      - ./dets:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: expense_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: detsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: